### ISSUE TITLE
How does it work? 

### ISSUE THREAD

**Issue by innerop** [JasonYangShadow/lpmx#21]
Very interesting work! But how does it actually do what it claims it does?

Is there a deacription aside from trying to figure out by reading the code? :)

Thank you for sharing!

**Comment by JasonYangShadow** [comment]
Thanks for being interested in this project.
Basically speaking, we use LD_PRELOAD to trap most of systemcalls requested by the target process running in host in order to implement our functions. Please see details in this project: https://github.com/jasonyangshadow/fakechroot

**Comment by JasonYangShadow** [comment]
> Very interesting work! But how does it actually do what it claims it does?
> 
> Is there a deacription aside from trying to figure out by reading the code? :)
> 
> Thank you for sharing!

Thanks for being interested in this project.
Basically speaking, we use LD_PRELOAD to trap most of systemcalls requested by the target process running in host in order to implement our functions. Please see details in this project: https://github.com/jasonyangshadow/fakechroot

**Comment by innerop** [comment]
Any differences you can sum up with respect to gVisor?

**Comment by innerop** [comment]
Hi. Ping ^^

**Comment by JasonYangShadow** [comment]
> Hi. Ping ^^

sorry for the late reply. It seems that gvisor is developed for integrating docker and kubernetes, so it is not suitable for HPC where root privilege is not satisfied. We are focusing on designing and developing pure rootless container targeting at solving dependencies hell problem.

**Comment by innerop** [comment]
Makes sense. Thank you!
