### ISSUE TITLE
Mount host directory

### ISSUE THREAD

**Issue by innerop** [JasonYangShadow/lpmx#22]
Hi

Anything similar to docker rum -v host-for:container-dir for mouting host directory in container? Assume an NFS volume I want to expose to the container. Is that possible?

**Comment by JasonYangShadow** [comment]
> Hi
> 
> Anything similar to docker rum -v host-for:container-dir for mouting host directory in container? Assume an NFS volume I want to expose to the container. Is that possible?

The current implementation is that when the first time you run LPMX, it will automatically create a folder named "sync" in the current working directory, each time when you create a new container with unique id auto-generated, a folder with the same container id is also created inside "sync" folder, where you can put anything inside this folder and they will be available under /lpmx inside container.

**Comment by innerop** [comment]
That’s ok but does it mean I can mount NFS to the sync folder?  My containers which can be on different machines need to access a shared folder. Would be so cool if I could use LPMX..

**Comment by JasonYangShadow** [comment]
> That’s ok but does it mean I can mount NFS to the sync folder? My containers which can be on different machines need to access a shared folder. Would be so cool if I could use LPMX..
Technically speaking, symlink inside "sync" folder will not be processed but I did not test that. Great advice, will note it down and retouch you later on the result.
The current issue is that libraries are built on very old glibc(2.5) in order for better compatibility, but it causes some unexpected issues, and I am working on fixing this issue.
Later I will share what distros are tested and supported, in theory, LPMX could support most major distros, but I do not have enough time to test all. Basically, ubuntu(14.04,16.04,18.04) and centos(6,7) should be supported in my plan.

**Comment by JasonYangShadow** [comment]
> That’s ok but does it mean I can mount NFS to the sync folder? My containers which can be on different machines need to access a shared folder. Would be so cool if I could use LPMX..

Technically speaking, symlink inside "sync" folder will not be processed but I did not test that. Great advice, will note it down and retouch you later on the result.
The current issue is that libraries are built on very old glibc(2.5) in order for better compatibility, but it causes some unexpected issues, and I am working on fixing this issue.
Later I will share what distros are tested and supported, in theory, LPMX could support most major distros, but I do not have enough time to test all. Basically, ubuntu(14.04,16.04,18.04) and centos(6,7) should be supported in my plan.

**Comment by JasonYangShadow** [comment]
> That’s ok but does it mean I can mount NFS to the sync folder? My containers which can be on different machines need to access a shared folder. Would be so cool if I could use LPMX..

Hey, from alpha-0.5, LPMX is supporting mounting host folder into the container by using "lpmx docker create -v Host_Path:Container_Path image_name". So I think we could close this issue.
