### ISSUE TITLE
Unknown userid can't get user info

### ISSUE THREAD

**Issue by unsupervisednn** [JasonYangShadow/lpmx#24]
I'm trying to run this on a limited system (a running docker container) where I only have non-root access. I get this error

```
$ ./lpmx docker create ubuntu:18.04
time="2020-03-08T03:55:25Z" level=fatal msg="\n**user: unknown userid 999** \ncan't get current user info\n"
```

Some relevant details:
```
$ whoami
whoami: cannot find name for user ID 999
$ id
uid=999 gid=0(root) groups=0(root)
$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/bin/false
container:x:1000:1000::/home/container:
```

**Comment by JasonYangShadow** [comment]
> 
> 
> I'm trying to run this on a limited system (a running docker container) where I only have non-root access. I get this error
> 
> ```
> $ ./lpmx docker create ubuntu:18.04
> time="2020-03-08T03:55:25Z" level=fatal msg="\n**user: unknown userid 999** \ncan't get current user info\n"
> ```
> 
> Some relevant details:
> 
> ```
> $ whoami
> whoami: cannot find name for user ID 999
> $ id
> uid=999 gid=0(root) groups=0(root)
> $ cat /etc/passwd
> root:x:0:0:root:/root:/bin/bash
> daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
> bin:x:2:2:bin:/bin:/usr/sbin/nologin
> sys:x:3:3:sys:/dev:/usr/sbin/nologin
> sync:x:4:65534:sync:/bin:/bin/sync
> games:x:5:60:games:/usr/games:/usr/sbin/nologin
> man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
> lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
> mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
> news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
> uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
> proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
> www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
> backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
> list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
> irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
> gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
> nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
> _apt:x:100:65534::/nonexistent:/bin/false
> container:x:1000:1000::/home/container:
> ```

Really sorry for the late reply.
Thank you so much for trying LPMX.
I tried to reproduce your scenario. 

Here is the output inside LPMX with fake root
![image](https://user-images.githubusercontent.com/2051711/82519387-86422600-9b5c-11ea-9af8-3aaec3cfc574.png)

Here is the output outside LPMX
![image](https://user-images.githubusercontent.com/2051711/82519476-c30e1d00-9b5c-11ea-8e83-2d1f465b63e1.png)

'newuser' is created via Dockerfile

Here is the Dockerfile
```
FROM ubuntu:18.04
RUN apt update && apt install -y --no-install-recommends wget build-essential ca-certificates
RUN useradd -ms /bin/bash newuser
USER newuser
WORKDIR /home/newuser
```

Compared to my test case and yours, I think the root cause is that the uid and gid of 'newuser' are different, in your case, 'newuser' belongs to root group, while in my case 'newuser' belongs to its own group. 

Thank you so much for the trial, I will patch LPMX for this issue.
