### ISSUE TITLE
Python write file error: device is busy

### ISSUE THREAD

**Issue by maytinhdibo** [JasonYangShadow/lpmx#27]
Can use `repo` command based on git and python support. How to mount an image disk.

**Comment by JasonYangShadow** [comment]
> Can use `repo` command based on git and python support. How to mount an image disk.

Thank you so much for trying LPMX. 

To mount an image disk, LPMX supports creating symlink when creating a container, such as:
```
-bash-4.1$ lpmx docker create
Error: accepts 1 arg(s), received 0
Usage:
  lpmx docker create [flags]

Flags:
  -h, --help            help for create
  -n, --name string     optional
  -v, --volume string   optional
```

```
lpmx docker create -v host_path:root_path ubuntu:16.04

For example:
lpmx docker create -v /tmp/folder:/mountdir ubunut:16.04
cd /mountdir && ls -al /mountdir
```
![image](https://user-images.githubusercontent.com/2051711/123531340-c7810e00-d73e-11eb-9986-9c464977793b.png)

If you have any further problems, please feel free to contact me!
