### ISSUE TITLE
Related tools

### ISSUE THREAD

**Issue by vsoch** [JasonYangShadow/lpmx#28]
Hi! I saw your repository and took a look - for related tools you can also include [Singularity Compose](http://singularityhub.github.io/singularity-compose), which does actual orchestration for Singularity containers (volumes, networking, etc.). Thanks!

**Comment by JasonYangShadow** [comment]
resolved in the commit https://github.com/JasonYangShadow/lpmx/commit/ebdc7223c74c6f11d73d52b5d8abc04c8d6a9d94

**Comment by vsoch** [comment]
Thank you!
