### ISSUE TITLE
Support configuration via YAML files

### ISSUE THREAD

**Issue by johanneskoester** [JasonYangShadow/lpmx#29]
Similar to the definition of Conda environments, it would be nice if LPMX would support to define a combination of images via a YAML based syntax, serving as the only input file for building and starting a corresponding composed environment.

**Comment by JasonYangShadow** [comment]
> Similar to the definition of Conda environments, it would be nice if LPMX would support to define a combination of images via a YAML based syntax, serving as the only input file for building and starting a corresponding composed environment.

thanks for the comment. Yes, it would be one of my goals to support YAML files. Actually, LPMX currently support reading YAML files such as https://github.com/JasonYangShadow/LPMXSettingRepository/blob/master/distro.management.yml 
but it does not have features of defining a combination of images via YAML files.

Anyway, it is so great that you are interested in LPMX and share the suggestion with me. Thanks! I will update here when the feature is added in the future.

**Comment by johanneskoester** [comment]
Hi Janson, any update or ETA on this?

**Comment by JasonYangShadow** [comment]
> Hi Janson, any update or ETA on this?

Oh, sorry that recently I am working on my Ph.D. thesis. I am currently working on this, I think there will be a release in early May. 😄

**Comment by johanneskoester** [comment]
Great to hear, thanks a lot!

**Comment by JasonYangShadow** [comment]
@johanneskoester , I have released a newer version of LPMX (alpha v2.0.1) to support creating containers via yaml files.
https://github.com/JasonYangShadow/lpmx/releases/tag/v2.0.1
😃

**Comment by JasonYangShadow** [comment]
I am working for creating a package for conda. The difficult point is that I need to configure LPMX to make it save data (image data and some dependencies) to somewhere else rather than conda directory.
