### ISSUE TITLE
Provide LPMX as a conda package

### ISSUE THREAD

**Issue by johanneskoester** [JasonYangShadow/lpmx#30]
It would be nice if LPMX could be installed via Conda, by hosting a package on conda-forge.

I am unsure in what way this statement here will make this hard:
> (We need supports from community!) Only several host OS are supported currently in this [repository](https://github.com/JasonYangShadow/LPMXSettingRepository) (Ubuntu 12.04/14.04/16.04/18.04/19.04, Centos 5.11/6/6.7/7), we compiled fakechroot against common Linux distros, but still there might be incompatability issues among different glibc versions. Common container image types are supported, such as Ubuntu and CentOS.

A start would be to have detailed compilation instructions in the readme, so that we can try to build a conda package from this. Alternatively, of course a direct PR to conda-forge/staged-recipes would be fine as well.

**Comment by JasonYangShadow** [comment]
@johanneskoester 
the only thing is that LPMX's dependency, i.e. libfakechroot (https://github.com/jasonyangshadow/fakechroot), requires different configurations against different distros, recently I also migrated to build libfakechroot against old Glibc (as we know, Glibc has strict backward-compatibility), I compiled libfakechroot against CentOS 6.10 with Glibc 2.12
(https://github.com/JasonYangShadow/LPMXSettingRepository/tree/master/v1.9/centos/6.10)
```
[vagrant@localhost ~]$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
and used this libfakechroot as the base version for different hosts.

Anyway, yes, I will help integrate LPMX with conda, and I think it would be a great move. Though I used to maintain a ppa repo for LPMX (https://github.com/JasonYangShadow/lpmx/releases/tag/v1.6.1), it is far more inefficient compared to Conda. Thanks for the suggestion, I will update you here when I make some progress in the future. Thanks!

**Comment by johanneskoester** [comment]
If I am not completely wrong for Bioconda and conda-forge, CentOS 7 with its glibc is currently the basis. There is even already a fakechroot package available: https://anaconda.org/conda-forge/fakechroot
Is that sufficient to build LPMX?

**Comment by JasonYangShadow** [comment]
> If I am not completely wrong for Bioconda and conda-forge, CentOS 7 with its glibc is currently the basis. There is even already a fakechroot package available: [anaconda.org/conda-forge/fakechroot](https://anaconda.org/conda-forge/fakechroot) Is that sufficient to build LPMX?

Yes, I also heard that CentOS 7 is used as the current base.
https://matrix.to/#/!MhHkICgthNLZeLiygG:gitter.im/$JescNhOzvtWUa2FBTGE0JnHOtcivic79YGr0uMfNg0s?via=gitter.im&via=matrix.org 
https://github.com/bioconda/bioconda-utils/blob/master/Dockerfile 

Yes. It is sufficient for building LPMX. Actually, I have built the dependency for LPMX on CentOS 7
https://github.com/JasonYangShadow/LPMXSettingRepository/tree/master/v1.9/centos/7
